package com.tweetapp.entities;

import java.util.Date;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.tweetapp.dto.Reply;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@DynamoDBTable(tableName = "tweets")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class TweetsEntity {

	@DynamoDBAttribute
	private String tweet;

	@DynamoDBAttribute
	private String userTweetId;

	@DynamoDBHashKey(attributeName = "tweetId")
	@DynamoDBAutoGeneratedKey
	private String tweetId;

	@DynamoDBAttribute
	private Long like;

	@DynamoDBAttribute
	private List<Reply> reply;

	@DynamoDBAttribute
	private Date dateOfPost;

	public String getTweet() {
		return tweet;
	}

	public void setTweet(String tweet) {
		this.tweet = tweet;
	}

	public String getUserTweetId() {
		return userTweetId;
	}

	public void setUserTweetId(String userTweetId) {
		this.userTweetId = userTweetId;
	}

	public String getTweetId() {
		return tweetId;
	}

	public void setTweetId(String tweetId) {
		this.tweetId = tweetId;
	}

	public Long getLike() {
		return like;
	}

	public void setLike(Long like) {
		this.like = like;
	}

	public List<Reply> getReply() {
		return reply;
	}

	public void setReply(List<Reply> reply) {
		this.reply = reply;
	}

	public Date getDateOfPost() {
		return dateOfPost;
	}

	public void setDateOfPost(Date dateOfPost) {
		this.dateOfPost = dateOfPost;
	}

}
